name: Release Docker Image

on:
  push:
    branches:
      - master

jobs:
  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ zibong }}
          password: ${{ dckr_pat_Yi0fVKyMRwaFJYMd8sM3odx8BOc }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zibong/image_name
