name: Release Docker Image

on:
  push:
    branches:
      - main  # Możesz zmienić na inną gałąź, jeśli to konieczne

jobs:
  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Krok 1: Pobranie kodu z repozytorium
      - name: Checkout code
        uses: actions/checkout@v2

      # Krok 2: Zalogowanie się do Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Krok 3: Budowa i wypchnięcie obrazu Dockera
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zbiong/image_name # Zastąp własnymi danymi