# Użycie lekkiego obrazu bazowego Pythona
FROM python:3.9-slim

# Ustawienie katalogu roboczego w kontenerze
WORKDIR /app

# Kopiowanie plików aplikacji do kontenera
COPY app /app

# Uruchamianie skryptu Python przy starcie kontenera
CMD ["python", "script.py"]
