version: '3.8'

networks:
  my_network:  # Definicja sieci Docker
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - my_network  # Przypisanie do niestandardowej sieci

  app:
    build: .
    container_name: python_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    networks:
      - my_network  # Przypisanie do niestandardowej sieci
